services:
  - type: web
    name: quizbattle-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install --no-cache-dir -r requirements.txt && python -m flask db upgrade && python init_db.py
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT wsgi:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: JWT_SECRET
        value: e57f70fc4fd74a56aa710c40ad11caaa
      - key: ADMIN_PASSWORD
        value: admin987
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_NY1EtTX5cqZH@ep-dawn-star-a1lemfrx-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: MONGO_URI
        value: mongodb+srv://quizbattle-db:4XPuEpIO2UUMemYR@cluster0.pzs2nrd.mongodb.net/quizbattle?retryWrites=true&w=majority&appName=Cluster0
      - key: CORS_ORIGINS
        value: "https://quizbattle-v2.netlify.app,https://www.quizbattle-v2.netlify.app"
