"""Increase admin password_hash column length to 256 characters

Revision ID: 3a1b2c3d4e5f
Revises: 2e115e6d2053
Create Date: 2025-09-16 06:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1b2c3d4e5f'
down_revision = '2e115e6d2053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
                              existing_type=sa.VARCHAR(length=128),
                              type_=sa.VARCHAR(length=256),
                              existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
                              existing_type=sa.VARCHAR(length=256),
                              type_=sa.VARCHAR(length=128),
                              existing_nullable=True)

    # ### end Alembic commands ###